controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    mecanum_velocity_controller:
      type: diff_drive_controller/DiffDriveController

mecanum_velocity_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.145
    wheel_radius: 0.05

    # Publish all joint states
    publish_rate: 50.0  # default: 50
    enable_odom_tf: true

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0  # m/s
        has_acceleration_limits: true
        max_acceleration: 0.5  # m/s^2
      y:
        has_velocity_limits: true
        max_velocity: 0.5  # m/s
        has_acceleration_limits: true
        max_acceleration: 0.25  # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.0  # rad/s^2