/controller_manager:
  ros__parameters:
    diagnostic_updater:
      period: 1.0
      use_fqn: false
    diagnostics:
      threshold:
        controller_manager:
          periodicity:
            mean_error:
              error: 10.0
              warn: 5.0
            standard_deviation:
              error: 10.0
              warn: 5.0
        controllers:
          execution_time:
            mean_error:
              error: 2000.0
              warn: 1000.0
            standard_deviation:
              error: 200.0
              warn: 100.0
          periodicity:
            mean_error:
              error: 10.0
              warn: 5.0
            standard_deviation:
              error: 10.0
              warn: 5.0
    hardware_components_initial_state:
      inactive: []
      unconfigured: []
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    mecanum_drive_controller:
      base_frame_id: base_link
      command_interfaces:
      - front_left_wheel_joint/velocity
      - front_right_wheel_joint/velocity
      - rear_left_wheel_joint/velocity
      - rear_right_wheel_joint/velocity
      enable_odom_tf: true
      front_left_wheel_command_joint_name: front_left_wheel_joint
      front_right_wheel_command_joint_name: front_right_wheel_joint
      odom_frame_id: odom
      open_loop: false
      publish_rate: 50.0
      rear_left_wheel_command_joint_name: rear_left_wheel_joint
      rear_right_wheel_command_joint_name: rear_right_wheel_joint
      type: mecanum_drive_controller/MecanumDriveController
      wheel_radius: 0.05
      wheel_separation_x: 0.175
      wheel_separation_y: 0.175
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    robot_description: '<?xml version="1.0" ?><!-- ===================================================================================
      --><!-- |    This document was autogenerated by xacro from /home/steve/mecca_ws/install/mecca_description/share/mecca_description/urdf/meccabot.xacro
      | --><!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 |
      --><!-- ===================================================================================
      --><robot name="meccabot_robot"><!-- now xacro: is bound for the entire file
      --><!-- Specify some standard inertial calculations https://en.wikipedia.org/wiki/List_of_moments_of_inertia
      --><!-- These make use of xacro''s mathematical functionality --><plugin filename="libgazebo_ros_diff_drive.so"
      name="diff_drive"><!-- Wheel Information --><left_joint>left_wheel_joint</left_joint><right_joint>right_wheel_joint</right_joint><wheel_separation>0.22</wheel_separation><wheel_diameter>0.08</wheel_diameter><!--
      Limits --><max_wheel_torque>200</max_wheel_torque><max_wheel_acceleration>10.0</max_wheel_acceleration><!--
      Output --><odometry_frame>odom</odometry_frame><robot_base_frame>base_link</robot_base_frame><publish_odom>true</publish_odom><publish_odom_tf>true</publish_odom_tf><publish_wheel_tf>true</publish_wheel_tf></plugin><!--
      Define Colors --><material name="white"><color rgba="1 1 1 1"/></material><material
      name="orange"><color rgba="1 0.3 0.1 1"/></material><material name="red"><color
      rgba="1 0 0 1"/></material><material name="blue"><color rgba="0.0 0.0 0.8 1.0"/></material><material
      name="green"><color rgba="0.2 0.9 0.2 1"/></material><material name="darkgrey"><color
      rgba="0.1 0.1 0.1 1.0"/></material><material name="grey"><color rgba="0.5 0.5
      0.5 1.0"/></material><material name="black"><color rgba="0 0 0 1"/></material><!--
      Base link --><link name="base_link"><inertial><origin rpy="0 0 0" xyz="0 0 0"/><mass
      value="0.1"/><inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0"
      izz="0.001"/></inertial></link><joint name="base_to_chassis" type="fixed"><parent
      link="base_link"/><child link="chassis_link"/><origin rpy="0 0 0" xyz="0 0 0.065"/></joint><!--
      Chassis --><link name="chassis_link"><inertial><origin rpy="0 0 0" xyz="0 0
      0.0625"/><mass value="5.0"/><inertia ixx="0.015270833333333332" ixy="0.0" ixz="0.0"
      iyy="0.03802083333333334" iyz="0.0" izz="0.04027083333333333"/></inertial><visual><origin
      rpy="0 0 0" xyz="0 0 0.0625"/><geometry><box size="0.275 0.145 0.125"/></geometry><material
      name="green"/></visual><collision><origin rpy="0 0 0" xyz="0 0 0.0625"/><geometry><box
      size="0.275 0.145 0.125"/></geometry></collision></link><joint name="front_left_wheel_joint"
      type="continuous"><parent link="chassis_link"/><child link="front_left_wheel"/><origin
      rpy="0 0 0" xyz="0.08750000000000001 0.0875 -0.015"/><axis xyz="0 1 0"/></joint><link
      name="front_left_wheel"><inertial><origin rpy="0 0 0" xyz="0 0 0"/><mass value="0.5"/><inertia
      ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/></inertial><visual><origin
      rpy="1.5708 0 0" xyz="0 0 0"/><geometry><cylinder length="0.03" radius="0.05"/></geometry><material
      name="grey"/></visual><collision><origin rpy="1.5708 0 0" xyz="0 0 0"/><geometry><cylinder
      length="0.03" radius="0.05"/></geometry></collision></link><joint name="front_right_wheel_joint"
      type="continuous"><parent link="chassis_link"/><child link="front_right_wheel"/><origin
      rpy="0 0 0" xyz="0.08750000000000001 -0.0875 -0.015"/><axis xyz="0 1 0"/></joint><link
      name="front_right_wheel"><inertial><origin rpy="0 0 0" xyz="0 0 0"/><mass value="0.5"/><inertia
      ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/></inertial><visual><origin
      rpy="1.5708 0 0" xyz="0 0 0"/><geometry><cylinder length="0.03" radius="0.05"/></geometry><material
      name="grey"/></visual><collision><origin rpy="1.5708 0 0" xyz="0 0 0"/><geometry><cylinder
      length="0.03" radius="0.05"/></geometry></collision></link><joint name="rear_left_wheel_joint"
      type="continuous"><parent link="chassis_link"/><child link="rear_left_wheel"/><origin
      rpy="0 0 0" xyz="-0.08750000000000001 0.0875 -0.015"/><axis xyz="0 1 0"/></joint><link
      name="rear_left_wheel"><inertial><origin rpy="0 0 0" xyz="0 0 0"/><mass value="0.5"/><inertia
      ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/></inertial><visual><origin
      rpy="1.5708 0 0" xyz="0 0 0"/><geometry><cylinder length="0.03" radius="0.05"/></geometry><material
      name="grey"/></visual><collision><origin rpy="1.5708 0 0" xyz="0 0 0"/><geometry><cylinder
      length="0.03" radius="0.05"/></geometry></collision></link><joint name="rear_right_wheel_joint"
      type="continuous"><parent link="chassis_link"/><child link="rear_right_wheel"/><origin
      rpy="0 0 0" xyz="-0.08750000000000001 -0.0875 -0.015"/><axis xyz="0 1 0"/></joint><link
      name="rear_right_wheel"><inertial><origin rpy="0 0 0" xyz="0 0 0"/><mass value="0.5"/><inertia
      ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/></inertial><visual><origin
      rpy="1.5708 0 0" xyz="0 0 0"/><geometry><cylinder length="0.03" radius="0.05"/></geometry><material
      name="grey"/></visual><collision><origin rpy="1.5708 0 0" xyz="0 0 0"/><geometry><cylinder
      length="0.03" radius="0.05"/></geometry></collision></link><!-- Lidar --><link
      name="lidar_mount"><visual><geometry><cylinder length="0.05" radius="0.04"/></geometry><material
      name="blue"/></visual><collision><geometry><cylinder length="0.05" radius="0.04"/></geometry></collision></link><joint
      name="lidar_joint" type="fixed"><parent link="base_link"/><child link="lidar_mount"/><origin
      rpy="0 0 0" xyz="-0.050 0 0.20500000000000002"/></joint><ros2_control name="MecanumRobot"
      type="system"><hardware><plugin>mecca_hardware_interface/MeccaHardware</plugin></hardware><!--
      Joint 1: Front Left Wheel --><joint name="front_left_wheel_joint"><command_interface
      name="velocity"/><state_interface name="velocity"/></joint><!-- Joint 2: Front
      Right Wheel --><joint name="front_right_wheel_joint"><command_interface name="velocity"/><state_interface
      name="velocity"/></joint><!-- Joint 3: Rear Left Wheel --><joint name="rear_left_wheel_joint"><command_interface
      name="velocity"/><state_interface name="velocity"/></joint><!-- Joint 4: Rear
      Right Wheel --><joint name="rear_right_wheel_joint"><command_interface name="velocity"/><state_interface
      name="velocity"/></joint></ros2_control></robot>'
    start_type_description_service: true
    update_rate: 30
    use_sim_time: false

