teleop_twist_joy_node:

  ros__parameters:

    enable_button: 5          # RB Button
    enable_turbo_button: 0    # A Button
    panic_button: 1           # B Button (for Emergency Stop)


    axis_linear:
      x: 1                    # Left Stick Fwd/Back
      y: 0                    # Left Stick Left/Right
      z: 0                    # Not used (Mecanum doesn't need vertical)

    axis_angular:
      yaw: 3                  # Right Stick Left/Right

    scale_linear:
      x: 1.0
      y: 1.0
      z: 0.0

    scale_angular:
      yaw: 1.4                # Adjust to control rotation speed

    scale_linear_turbo:
      x: 2.0
      y: 2.0
      z: 0.0

    scale_angular_turbo:
      yaw: 2.0                # Faster rotation in Turbo mode

    