controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    mecanum_drive_controller:
      type: "mecanum_drive_controller/MecanumDriveController"
      front_left_wheel_command_joint_name: front_left_wheel_joint
      rear_left_wheel_command_joint_name: rear_left_wheel_joint
      front_right_wheel_command_joint_name: front_right_wheel_joint
      rear_right_wheel_command_joint_name: rear_right_wheel_joint
      wheel_separation_x: 0.35
      wheel_separation_y: 0.28
      wheel_radius: 0.05
      base_frame_id: base_link
      odom_frame_id: odom
      open_loop: false
      enable_odom_tf: true
      publish_rate: 50.0

    joint_broad:
      type: "joint_state_broadcaster/JointStateBroadcaster"
