controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: false

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController
      front_left_wheel_command_joint_name: "front_left_wheel_joint"
      front_right_wheel_command_joint_name: "front_right_wheel_joint"
      rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
      rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
      
      wheel_separation_x: 0.175
      wheel_separation_y: 0.175
      wheel_radius: 0.05

      odom_frame_id: odom
      base_frame_id: base_link

      publish_rate: 50.0
      open_loop: false
      enable_odom_tf: true
